//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGEA_DS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comite()
        {
            this.MiembroComite = new HashSet<MiembroComite>();
            this.Actrividad = new HashSet<Actrividad>();
        }
    
        public int Id { get; set; }
        public string descripcion { get; set; }
        public string nombre { get; set; }
        public int EventoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiembroComite> MiembroComite { get; set; }
        public virtual Evento Evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actrividad> Actrividad { get; set; }
    }
}
