//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGEA_DS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingreso()
        {
            this.RegistroArticulo = new HashSet<RegistroArticulo>();
        }
    
        public int Id { get; set; }
        public string concepto { get; set; }
        public System.DateTime fecha { get; set; }
        public double monto { get; set; }
        public int ActrividadId { get; set; }
        public int AsistenteId { get; set; }
    
        public virtual Actrividad Actrividad { get; set; }
        public virtual Asistente Asistente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroArticulo> RegistroArticulo { get; set; }
        public virtual Patrocinador Patrocinador { get; set; }
    }
}
