//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGEA_DS.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroArticulo
    {
        public int Id { get; set; }
        public string comprobantePago { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public double Pago { get; set; }
        public int ArticuloId { get; set; }
        public int IngresoId { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Articulo Articulo { get; set; }
        public virtual Ingreso Ingreso { get; set; }
    }
}
