//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActividadSet()
        {
            this.ArticuloSets = new HashSet<ArticuloSet>();
            this.CalendarioSets = new HashSet<CalendarioSet>();
            this.MagistralSets = new HashSet<MagistralSet>();
            this.MaterialSets = new HashSet<MaterialSet>();
            this.TareaSets = new HashSet<TareaSet>();
            this.AsistenteSets = new HashSet<AsistenteSet>();
            this.ParticipanteSets = new HashSet<ParticipanteSet>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public double costo { get; set; }
        public string aula { get; set; }
        public string tipo { get; set; }
        public int EventoId { get; set; }
        public int ComiteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticuloSet> ArticuloSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendarioSet> CalendarioSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MagistralSet> MagistralSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSet> MaterialSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TareaSet> TareaSets { get; set; }
        public virtual ComiteSet ComiteSet { get; set; }
        public virtual EventoSet EventoSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsistenteSet> AsistenteSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipanteSet> ParticipanteSets { get; set; }
    }
}
