//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArticuloSet()
        {
            this.EvaluacionSets = new HashSet<EvaluacionSet>();
            this.RegistroArticuloSets = new HashSet<RegistroArticuloSet>();
        }
    
        public int Id { get; set; }
        public string @abstract { get; set; }
        public byte documento { get; set; }
        public int ActividadArticulo_Articulo_Id { get; set; }
    
        public virtual ActividadSet ActividadSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionSet> EvaluacionSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroArticuloSet> RegistroArticuloSets { get; set; }
    }
}
