//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgresoSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EgresoSet()
        {
            this.MaterialSets = new HashSet<MaterialSet>();
        }
    
        public int Id { get; set; }
        public string concepto { get; set; }
        public double monto { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> Magistral_Id { get; set; }
    
        public virtual MagistralSet MagistralSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSet> MaterialSets { get; set; }
    }
}
