//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionSet
    {
        public int Id { get; set; }
        public int calificacion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public int ArticuloId { get; set; }
        public int MiembroComite_Id { get; set; }
    
        public virtual ArticuloSet ArticuloSet { get; set; }
        public virtual MiembroComiteSet MiembroComiteSet { get; set; }
    }
}
