//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Evento
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Evento()
    {
        this.ActividadSet = new HashSet<Actividad>();
        this.ComiteSet = new HashSet<Comite>();
    }

    public int Id { get; set; }
    public string nombre { get; set; }
    public System.DateTime fechaInicio { get; set; }
    public System.DateTime fechaFin { get; set; }
    public string lugar { get; set; }
    public string institucionOrganizadora { get; set; }
    public Nullable<int> EventoPresupuesto_Evento_Id { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Actividad> ActividadSet { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comite> ComiteSet { get; set; }
    public virtual Presupuesto PresupuestoSet { get; set; }

    public override String ToString()
    {
        return nombre;
    }
}
