//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialSet
    {
        public int Id { get; set; }
        public string tipo { get; set; }
        public int cantidad { get; set; }
        public double costo { get; set; }
        public int ActividadId { get; set; }
        public int EgresoMaterial_Material_Id { get; set; }
    
        public virtual ActividadSet ActividadSet { get; set; }
        public virtual EgresoSet EgresoSet { get; set; }
    }
}
