//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiembroComite
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string correoElectronico { get; set; }
        public string nivelExperiencia { get; set; }
        public bool liderComite { get; set; }
        public int ComiteId { get; set; }
        public string nombreUsuario { get; set; }
        public string contrasenia { get; set; }
        public bool evaluador { get; set; }
    
        public virtual Comite Comite { get; set; }
    }
}
