//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatrocinadorSet
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string correoElectronico { get; set; }
        public string empresa { get; set; }
        public string direccion { get; set; }
        public string numeroTelefono { get; set; }
        public int IngresoPatrocinador_Patrocinador_Id { get; set; }
    
        public virtual IngresoSet IngresoSet { get; set; }
    }
}
