//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class RegistroArticulo
{
    public int Id { get; set; }
    public byte comprobantePago { get; set; }
    public System.DateTime fecha { get; set; }
    public System.TimeSpan hora { get; set; }
    public double cantidadPago { get; set; }
    public int AutorId { get; set; }

    public virtual Articulo Articulo { get; set; }
    public virtual Autor Autor { get; set; }
}
