//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroArticuloSet
    {
        public int Id { get; set; }
        public byte comprobantePago { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public double cantidadPago { get; set; }
        public int AutorId { get; set; }
        public int Articulo_Id { get; set; }
        public int RegistroArticuloIngreso_RegistroArticulo_Id { get; set; }
    
        public virtual ArticuloSet ArticuloSet { get; set; }
        public virtual AutorSet AutorSet { get; set; }
        public virtual IngresoSet IngresoSet { get; set; }
    }
}
